Add check for release notes update.

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -92,3 +92,30 @@ jobs:
         run: |
           set -e
           bash scripts/gha/check_copyright.sh -g
+
+  release_notes_check:
+    # Check that the readme was updated, unless the PR has the 'no-release-notes' flag.
+    runs-on: ubuntu-latest
+    # Don't bother doing this if the PR is already closed or has the no-release-notes label.
+    if: github.event.pull_request.state == 'open' && !contains(github.event.issue.labels.*.name, 'no-release-notes')
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          submodules: false
+      - name: Check if readme has been modified vs. the base ref.
+        run: |
+          set -e
+          # Filename to check.
+          README_FILE=release_build_files/readme.md
+          # Determine the github merge base - same logic as integration_tests.yml
+          # "git merge-base main branch_name" will give the common ancestor of both branches.
+          MERGE_BASE=$(git merge-base origin/${{github.event.pull_request.head.ref}} origin/${{github.event.pull_request.base.ref}} || true)
+          # If MERGE_BASE can't be determined, just use "main"
+          if [[ -z "${MERGE_BASE}" ]]; then
+            MERGE_BASE=main
+          fi
+          DIFF_RESULT_=$(git diff --name-only "${MERGE_BASE}" -- "${README_FILE}")
+          if [[ "${DIFF_RESULT}" != "${README_FILE}" ]]; then
+            echo "::error :Please update release notes (${README_FILE}) or add no-release-notes label."
+            exit 1
+          fi
