cpp-packaging.yml: add back build_tools

diff --git a/.github/workflows/cpp-packaging.yml b/.github/workflows/cpp-packaging.yml
--- a/.github/workflows/cpp-packaging.yml
+++ b/.github/workflows/cpp-packaging.yml
@@ -73,6 +73,107 @@ jobs:
         if: github.event_name == 'schedule' || github.event.inputs.use_expanded_matrix == '1'
         run: echo "::warning ::Expanded test matrix enabled."
 
+  build_tools:
+    name: build-tools-${{ matrix.tools_platform }}
+    runs-on: ${{ matrix.os }}
+    if: ${{ github.event.inputs.downloadPublicVersion == '' && github.event.inputs.downloadPreviousRun == '' }}
+    strategy:
+      matrix:
+        os: [ubuntu-latest]
+        include:
+        - os: ubuntu-latest
+          tools_platform: linux
+          # Binutils 2.35.1 released Sep 19, 2020
+          binutils_version: "2.35.1"
+    steps:
+      - name: setup Xcode version (macos)
+        if: runner.os == 'macOS'
+        run: sudo xcode-select -s /Applications/Xcode_${{ env.xcodeVersion }}.app/Contents/Developer
+
+      - name: Fetch and build binutils
+        run: |
+          set +e
+          # Retry up to 10 times because Curl has a tendency to timeout on
+          # Github runners.
+          for retry in {1..10} error; do
+          if [[ $retry == "error" ]]; then exit 5; fi
+            curl -L https://ftpmirror.gnu.org/binutils/binutils-${{ matrix.binutils_version }}.tar.xz --output binutils.tar.xz && break
+            sleep 300
+          done
+          set -e
+
+          tar -xf binutils.tar.xz
+          mv ./binutils-${{ matrix.binutils_version }} ./binutils-src
+          mkdir /tmp/binutils-output
+          cd binutils-src
+          ./configure --enable-targets=all --prefix=/tmp/binutils-output
+          make -j2
+          make install
+          cd -
+          mkdir -p packaging-tools
+          cp -af /tmp/binutils-output/bin/* packaging-tools
+
+      - name: Cache LLVM (Mac only)
+        if: matrix.tools_platform == 'darwin'
+        id: cache_llvm
+        uses: actions/cache@v2
+        with:
+          path: llvm-src/llvm/build/bin
+          key: llvm-bin-${{matrix.tools_platform}}-${{env.xcodeVersion}}-${{env.llvmVer}}
+
+      - name: Fetch LLVM source (Mac only)
+        # Only fetch LLVM if we don't already have binaries from the cache.
+        if: ${{ matrix.tools_platform == 'darwin' && !steps.cache_llvm.outputs.cache-hit }}
+        uses: actions/checkout@v2.3.1
+        with:
+          repository: llvm/llvm-project
+          path: llvm-src
+          ref: ${{ env.llvmVer }}
+
+      - name: Build LLVM (Mac only) 
+        # Only build LLVM if we don't already have binaries from the cache.
+        if: ${{ matrix.tools_platform == 'darwin' && !steps.cache_llvm.outputs.cache-hit }}
+        run: |
+          mkdir llvm-src/llvm/build
+          cd llvm-src/llvm/build
+          cmake -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_BUILD_TYPE=Release ..
+          cmake --build . -j 3 --target llvm-objcopy --target llvm-nm --target llvm-ar
+
+      - name: Package LLVM output (Mac only)
+        if: matrix.tools_platform == 'darwin'
+        run: |
+          mkdir -p packaging-tools
+          cp -af llvm-src/llvm/build/bin/* packaging-tools
+
+      - name: fetch demumble
+        uses: actions/checkout@v2.3.1
+        with:
+          repository: nico/demumble
+          path: demumble-src
+          ref: v${{ env.demumbleVer }}
+
+      - name: build demumble
+        run: |
+          cd demumble-src
+          cmake .
+          cmake --build .
+          python demumble_test.py
+          cd -
+          mkdir -p packaging-tools
+          cp -af demumble-src/demumble packaging-tools
+
+      - name: archive tools
+        run: |
+          cd packaging-tools
+          ls
+          tar -czhf ../packaging-tools.tgz .
+
+      - name: upload artifacts
+        uses: actions/upload-artifact@v2.2.2
+        with:
+          name: packaging-tools-${{ matrix.tools_platform }}
+          path: packaging-tools.tgz
+
   build_desktop:
     name: build-${{ matrix.sdk_platform }}-${{ matrix.architecture }}-${{ matrix.build_type }}-${{ matrix.msvc_runtime }}-${{ matrix.linux_abi }}
     runs-on: ${{ matrix.os }}
@@ -232,7 +333,7 @@ jobs:
   package_desktop:
     name: package-${{ matrix.sdk_platform }}${{ matrix.suffix }}
     runs-on: ${{ matrix.runs_on_platform }}
-    needs: [build_desktop]
+    needs: [build_tools, build_desktop]
     if: ${{ github.event.inputs.downloadPublicVersion == '' && github.event.inputs.downloadPreviousRun == '' }}
     strategy:
       fail-fast: false
