mac os diagnostic reports now in /tmp/cores

diff --git a/.github/workflows/desktop.yml b/.github/workflows/desktop.yml
--- a/.github/workflows/desktop.yml
+++ b/.github/workflows/desktop.yml
@@ -165,8 +165,6 @@ jobs:
 
       - name: Enable crash support (linux)
         # Ensures directory structure is in place to capture core files on Linux. 
-        # Note that the ulimit call to enable crashes must be done in the process
-        # which runs the ctest executable and cannot be placed here.
         if: startsWith(matrix.build_type, 'Debug') && startsWith(matrix.os, 'ubuntu')
         shell: bash
         run: |
@@ -175,8 +173,7 @@ jobs:
           sudo rm -rf /tmp/cores/*
           
       - name: Enable crash support (mac)
-        # Clears out all of the older crahes in case they exist on the same
-        # VM instance and/or have been cahced.
+        # Ensures no lingering crashes from a previous run.
         if: startsWith(matrix.os, 'macos')
         run: |
           rm -rf ~/Library/Logs/DiagnosticReports/*
@@ -191,7 +188,8 @@ jobs:
 
       - name: Run tests (linux)
         # Linux exists as its own standalone execution step in order to invoke
-        # ulimit to enable crash collection.
+        # platform-specific ulimit to enable crash collection.  The ulimit command
+        # must be made in same instance of the shell that runs the tests.
         if: startsWith(matrix.os, 'ubuntu')
         env:
           LANG: en_US
@@ -202,44 +200,27 @@ jobs:
       
       - name: Prep bins for achive (linux)
         # Copies all of the binary files into one directory for ease in
-        # archiving. Directory are name-mangled by build configuration and
-        # marked readable by the archive step.
-          # sudo rm -rf /tmp/upload/bins/* || :
-          # sudo mkdir -p /tmp/upload/bins/${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}
-          # sudo rm -rf ./build/app/tests/firebase_test
-          # sudo cp -f ./build/analytics/tests/firebase* /tmp/upload/bins/${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}
-          # sudo cp -f ./build/app/tests/firebase* /tmp/upload/bins/${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}
-          # sudo cp -f ./build/app/rest/tests/firebase* /tmp/upload/bins/${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}
-          # sudo cp -f ./build/auth/tests/firebase* /tmp/upload/bins/${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}
-          # sudo cp -f ./build/database/tests/firebase* /tmp/upload/bins/${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}
-          # sudo cp -f ./build/instance_id/tests/firebase* /tmp/upload/bins/${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}
-          # sudo cp -f ./build/remote_config/tests/firebase* /tmp/upload/bins/${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}
-          # sudo cp -f ./build/storage/tests/firebase* /tmp/upload/bins/${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}
-
+        # archiving. Directory contents are then marked readable for the
+        # archive step.
         if: failure() && startsWith(matrix.build_type, 'Debug') && ( startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos') )
         shell: bash
         run: |
-          sudo rm -rf /tmp/upload/bins/* || :
-          sudo mkdir -p /tmp/upload/bins/
+          sudo rm -rf /tmp/bins/* || :
+          sudo mkdir -p /tmp/bins/
           sudo rm -rf ./build/app/tests/firebase_test
-          sudo cp -f ./build/analytics/tests/firebase* /tmp/upload/bins/
-          sudo cp -f ./build/app/tests/firebase* /tmp/upload/bins/
-          sudo cp -f ./build/app/rest/tests/firebase* /tmp/upload/bins/
-          sudo cp -f ./build/auth/tests/firebase* /tmp/upload/bins/
-          sudo cp -f ./build/database/tests/firebase* /tmp/upload/bins/
-          sudo cp -f ./build/instance_id/tests/firebase* /tmp/upload/bins/
-          sudo cp -f ./build/remote_config/tests/firebase* /tmp/upload/bins/
-          sudo cp -f ./build/storage/tests/firebase* /tmp/upload/bins/
-          sudo chmod -R +rwx /tmp/upload/bins/* || :
-  
+          sudo cp -f ./build/analytics/tests/firebase* /tmp/bins/
+          sudo cp -f ./build/app/tests/firebase* /tmp/bins/
+          sudo cp -f ./build/app/rest/tests/firebase* /tmp/bins/
+          sudo cp -f ./build/auth/tests/firebase* /tmp/bins/
+          sudo cp -f ./build/database/tests/firebase* /tmp/bins/
+          sudo cp -f ./build/instance_id/tests/firebase* /tmp/bins/
+          sudo cp -f ./build/remote_config/tests/firebase* /tmp/bins/
+          sudo cp -f ./build/storage/tests/firebase* /tmp/bins/
+          sudo chmod -R +rwx /tmp/bins/* || :
 
       - name: Prep crash data for archive (linux)
-        # Copies all core files into a directory name-mangled by build
-        # configuration and marks them readable for the archiving step.
-          # sudo rm -rf /tmp/upload/cores/${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}/*   || :
-          # sudo mkdir -p /tmp/upload/cores/${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}
-          # sudo cp -r /tmp/cores/* /tmp/upload/cores/${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}
-          # sudo chmod -R +rwx /tmp/upload/cores/* || :
+        # Marks the contents of the core dump directory to be readable for the
+        # archiving step.
         shell: bash
         if: failure() && startsWith(matrix.build_type, 'Debug') && startsWith(matrix.os, 'ubuntu')
         run: |
@@ -250,48 +231,47 @@ jobs:
         shell: bash
         if: failure() && startsWith(matrix.build_type, 'Debug') && startsWith(matrix.os, 'macos')
         run: |
-          sudo chmod -R +rwx ~/Library/Logs/DiagnosticReports/* || : 
-      
-      - name: Archive crashes and binaries (linux - makefiles)
-        # Unfortunately matrix.generator includes spaces for Unix Makefiles, so 
-        # we cannot use it to name-mangle archive files. Therefore there are 
-        # different archive steps for Makefiles and Ninja generated builds
-        # for both Mac and Linux.
-          # /tmp/upload/cores/${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}
-          #  /tmp/upload/bins/${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}
+          sudo rm -rf /tmp/cores/* || :
+          sudo mkdir -p /tmp/cores/
+          sudo cp  ~/Library/Logs/DiagnosticReports/* /tmp/cores
+          sudo chmod -R +rwx /tmp/cores || : 
+
+      # Crash Archives - Unfortunately matrix.generator includes spaces for
+      # the "Unix Makefiles" configuration so it cannot be used to name-mangle
+      # archive files. Instead there are different steps for Ninja & Makfiles
+      # archive uploads.
+      - name: Archive crashes and binaries (Unix makefiles)
         uses: actions/upload-artifact@v2
-        if: failure() && startsWith(matrix.generator, 'Unix Makefiles') && startsWith(matrix.build_type, 'Debug') && startsWith(matrix.os, 'ubuntu')
+        if: failure() && startsWith(matrix.generator, 'Unix Makefiles') && startsWith(matrix.build_type, 'Debug') && (startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos'))
         with:
           name: crashes-${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}-makefiles
           path: |
             /tmp/cores/*
-            /tmp/upload/bins/*
+            /tmp/bins/*
       
-      - name: Archive crashes and binaries (linux - ninja )
+      - name: Archive crashes and binaries (ninja)
         uses: actions/upload-artifact@v2
-        if: failure() && startsWith(matrix.generator, 'Ninja') && startsWith(matrix.build_type, 'Debug') && startsWith(matrix.os, 'ubuntu')
+        if: failure() && startsWith(matrix.generator, 'Ninja') && startsWith(matrix.build_type, 'Debug') && (startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos'))
         with:
           name: crashes-${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}-ninja
           path: |
             /tmp/cores/*
-            /tmp/upload/bins/*
-          # /tmp/upload/cores/${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}
-          # /tmp/upload/bins/${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}
+            /tmp/bins/*
 
-      - name: Archive crashes (mac - makefiles)
-        uses: actions/upload-artifact@v2
-        if: failure() && startsWith(matrix.generator, 'Unix Makefiles') && startsWith(matrix.build_type, 'Debug') && startsWith(matrix.os, 'macos')
-        with:
-          name: crashes-${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}-makefiles
-          path: |
-            ~/Library/Logs/DiagnosticReports/*
-            /tmp/upload/bins/*
+      #- name: Archive crashes (mac - makefiles)
+      #  uses: actions/upload-artifact@v2
+      #  if: failure() && startsWith(matrix.generator, 'Unix Makefiles') && startsWith(matrix.build_type, 'Debug') && startsWith(matrix.os, 'macos')
+      #  with:
+      #    name: crashes-${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}-makefiles
+      #    path: |
+      #      ~/Library/Logs/DiagnosticReports/*
+      #      /tmp/bins/*
 
-      - name: Archive crashes (mac - ninja)
-        uses: actions/upload-artifact@v2
-        if: failure() && startsWith(matrix.generator, 'Ninja') && startsWith(matrix.build_type, 'Debug') && startsWith(matrix.os, 'macos')
-        with:
-          name: crashes-${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}-ninja
-          path: |
-            ~/Library/Logs/DiagnosticReports/*
-            /tmp/upload/bins/*
+      #- name: Archive crashes (mac - ninja)
+      #  uses: actions/upload-artifact@v2
+      #  if: failure() && startsWith(matrix.generator, 'Ninja') && startsWith(matrix.build_type, 'Debug') && startsWith(matrix.os, 'macos')
+      #  with:
+      #    name: crashes-${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.python_version }}-ninja
+      #    path: |
+      #      ~/Library/Logs/DiagnosticReports/*
+      #      /tmp/bins/*
