Add architecture to desktop integration test logs.
Add custom runner for arm64 mac support.

Enable x86 Linux/Windows tests.

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -46,7 +46,11 @@ env:
   pythonVersion: '3.7'
   artifactRetentionDays: 2
   GITHUB_TOKEN: ${{ github.token }}
-
+  # All self-hosted ARM Mac runners should have this label. Due to how
+  # our custom reporting works, it must be exactly two words separated
+  # by a hyphen. The first word must be "macos". The second word will
+  # be omitted from the summary log.
+  runnerLabelMacArm64: 'macos-m1custom'
 jobs:
   check_and_prepare:
     runs-on: ubuntu-latest
@@ -56,6 +60,9 @@ jobs:
       pr_number: ${{ steps.set_outputs.outputs.pr_number }}
       matrix_platform: ${{ steps.matrix_config.outputs.matrix_platform }}
       matrix_os: ${{ steps.matrix_config.outputs.matrix_os }}
+      matrix_arch_macos: ${{ steps.matrix_config.outputs.matrix_arch_macos }}
+      matrix_arch_windows_linux: ${{ steps.matrix_config.outputs.matrix_arch_windows_linux }}
+      matrix_arch_combined: ${{ steps.matrix_config.outputs.matrix_arch_combined }}
       matrix_ssl: ${{ steps.matrix_config.outputs.matrix_ssl }}
       apis: ${{ steps.matrix_config.outputs.apis }}
       mobile_test_on: ${{ steps.matrix_config.outputs.mobile_test_on }}
@@ -63,6 +70,8 @@ jobs:
       xcode_version: ${{ steps.matrix_config.outputs.xcode_version }}
       ios_device: ${{ steps.matrix_config.outputs.ios_device }}
       tvos_device: ${{ steps.matrix_config.outputs.tvos_device }}
+      # Copy the runner label here because matrix specifiers cannot see env.
+      runner_label_mac_arm64: ${{ env.runnerLabelMacArm64 }}
     steps:
     ### Fail the workflow if the user does not have admin access to run the tests.
     - name: Check if user has permission to trigger tests
@@ -183,11 +192,20 @@ jobs:
         echo "::set-output name=apis::${apis}"
         echo "::set-output name=matrix_platform::$( python scripts/gha/print_matrix_configuration.py -w integration_tests ${TEST_MATRIX_PARAM} -k platform -o "${{github.event.inputs.platforms}}" --apis ${apis} )"
         echo "::set-output name=matrix_os::$( python scripts/gha/print_matrix_configuration.py -w integration_tests ${TEST_MATRIX_PARAM} -k os -o "${{github.event.inputs.operating_systems}}")"
-        # If building against a packaged SDK, only use boringssl.
+        echo "::set-output name=matrix_arch_macos::$( python scripts/gha/print_matrix_configuration.py -w integration_tests ${TEST_MATRIX_PARAM} -k architecture_macos)"
+        echo "::set-output name=matrix_arch_windows_linux::$( python scripts/gha/print_matrix_configuration.py -w integration_tests ${TEST_MATRIX_PARAM} -k architecture_windows_linux)"
+        # Combine architecture_macos and architecture_windows_linux to get a list of all architectures for the build matrix.
+        matrix_arch_combined=`echo $( python scripts/gha/print_matrix_configuration.py -w integration_tests ${TEST_MATRIX_PARAM} -k architecture_macos | sed 's/[]\[,]//g') \
+                                   $( python scripts/gha/print_matrix_configuration.py -w integration_tests ${TEST_MATRIX_PARAM} -k architecture_windows_linux | sed 's/[]\[,]//g' ) \
+                                   | sed 's/ /\n/g' | sort | uniq`
+        matrix_arch_combined_json=["$(echo ${matrix_arch_combined} | sed 's/ /,/g')"]
+        echo "::set-output name=matrix_arch_combined::${matrix_arch_combined_json}"
+        # If building against a packaged SDK, consider it as using boringssl, as the packaged SDK uses boringssl under the hood.
+        # This avoids trying to install openssl on the system when compiling against the packaged SDK.
+        # As an added bonus, we ensure that the packaged SDK works even without openssl explicitly installed.
         if [[ -n "${{ github.event.inputs.test_packaged_sdk }}" ]]; then
           echo "::warning ::Downloading SDK package from previous run: https://github.com/${{github.repository}}/actions/runs/${{ github.event.inputs.test_packaged_sdk }}"
-          # Because the mobile tests require this value to be set to 'openssl', set it to 'openssl' here. It won't actually matter later.
-          echo "::set-output name=matrix_ssl::$( python scripts/gha/print_matrix_configuration.py -w integration_tests ${TEST_MATRIX_PARAM} -k ssl_lib -o openssl )"
+          echo "::set-output name=matrix_ssl::$( python scripts/gha/print_matrix_configuration.py -w integration_tests ${TEST_MATRIX_PARAM} -k ssl_lib -o boringssl )"
         else
           echo "::set-output name=matrix_ssl::$( python scripts/gha/print_matrix_configuration.py -w integration_tests ${TEST_MATRIX_PARAM} -k ssl_lib -o "${{github.event.inputs.desktop_ssl_variants}}" )"
         fi
@@ -209,7 +227,7 @@ jobs:
           --run_id ${{github.run_id}}
 
   build_desktop:
-    name: build-desktop-${{ matrix.os }}-${{ matrix.ssl_variant }}
+    name: build-desktop-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.ssl_variant }}
     needs: [check_and_prepare]
     runs-on: ${{ matrix.os }}
     # Skip this if there is an empty matrix (which can happen if "auto" was set above).
@@ -219,8 +237,25 @@ jobs:
       fail-fast: false
       matrix:
         os: ${{ fromJson(needs.check_and_prepare.outputs.matrix_os) }}
+        arch: ${{ fromJson(needs.check_and_prepare.outputs.matrix_arch_combined) }}
         ssl_variant: ${{ fromJson(needs.check_and_prepare.outputs.matrix_ssl) }}
-    steps:
+        # Because matrix_arch_combined combines mac, linux, and windows, we need a few exclusions.
+        exclude:
+          # Do not attempt to build for arm64 on Windows or Linux.
+        - os: windows-latest
+          arch: arm64
+        - os: ubuntu-latest
+          arch: arm64
+          # Do not attempt to build for x86 on Mac.
+        - os: macos-12
+          arch: x86
+          # Until we support building openssl from source, we can't link to system openssl when cross-compiling.
+          # Builds all happen on x64 machines, so arm64 and x86 are technically cross-compiling.
+        - ssl_variant: openssl
+          arch: arm64 
+        - ssl_variant: openssl
+          arch: x86
+   steps:
       - name: setup Xcode version (macos)
         if: runner.os == 'macOS'
         run: sudo xcode-select -s /Applications/Xcode_${{ fromJson(needs.check_and_prepare.outputs.xcode_version)[0] }}.app/Contents/Developer
@@ -335,7 +370,7 @@ jobs:
           python scripts/gha/build_testapps.py --p Desktop \
             --t ${{ needs.check_and_prepare.outputs.apis }} \
             --output_directory "${{ github.workspace }}" \
-            --artifact_name "desktop-${{ matrix.os }}-${{ matrix.ssl_variant }}" \
+            --artifact_name "desktop-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.ssl_variant }}" \
             --noadd_timestamp \
             --short_output_paths \
             ${additional_flags[*]}
@@ -343,28 +378,28 @@ jobs:
         if: ${{ !cancelled() }}
         shell: bash
         run: |
-          if [ ! -f build-results-desktop-${{ matrix.os }}-${{ matrix.ssl_variant }}.log.json ]; then
+          if [ ! -f build-results-desktop-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.ssl_variant }}.log.json ]; then
             # No summary was created, make a placeholder one.
-            echo "__SUMMARY_MISSING__" > build-results-desktop-${{ matrix.os }}-${{ matrix.ssl_variant }}.log.json
+            echo "__SUMMARY_MISSING__" > build-results-desktop-${{ matrix.os }}-${{ matrix.arch}}-${{ matrix.ssl_variant }}.log.json
           fi
       - name: Upload Desktop integration tests artifact
         uses: actions/upload-artifact@v3
         if: ${{ !cancelled() }}
         with:
-          name: testapps-desktop-${{ matrix.os }}-${{ matrix.ssl_variant }}
-          path: testapps-desktop-${{ matrix.os }}-${{ matrix.ssl_variant }}
+          name: testapps-desktop-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.ssl_variant }}
+          path: testapps-desktop-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.ssl_variant }}
           retention-days: ${{ env.artifactRetentionDays }}
       - name: Upload Desktop build results artifact
         uses: actions/upload-artifact@v3
         if: ${{ !cancelled() }}
         with:
           name: log-artifact
-          path: build-results-desktop-${{ matrix.os }}-${{ matrix.ssl_variant }}*
+          path: build-results-desktop-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.ssl_variant }}*
           retention-days: ${{ env.artifactRetentionDays }}
       - name: Cleanup Local Copies of Uploaded Artifacts
         shell: bash
         run: |
-          rm -rf testapps-desktop-${{ matrix.os }}-${{ matrix.ssl_variant }}
+          rm -rf testapps-desktop-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.ssl_variant }}
       - name: Set CLOUDSDK_PYTHON (Windows)
         shell: bash
         if: startsWith(matrix.os, 'windows') && !cancelled()
@@ -398,7 +433,7 @@ jobs:
         if: ${{ !cancelled() }}
         shell: bash
         run: |
-          cat build-results-desktop-${{ matrix.os }}-${{ matrix.ssl_variant }}.log
+          cat build-results-desktop-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.ssl_variant }}.log
           if [[ "${{ job.status }}" != "success" ]]; then
             exit 1
           fi
@@ -859,6 +894,148 @@ jobs:
             exit 1
           fi
 
+  # Run tests that depend on custom (self-hosted) runners.
+  # For now, this is only used for ARM Mac builds.
+  test_desktop_custom_runners:
+    name: test-desktop-selfhosted-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.ssl_variant }}
+    needs: [check_and_prepare, build_desktop]
+    runs-on: [self-hosted, firebase-cpp, '${{ matrix.runner_label }}' ]
+    if: |
+        needs.check_and_prepare.outputs.apis != '' &&
+        !cancelled()
+    strategy:
+      fail-fast: false
+      matrix:
+        ssl_variant: ${{ fromJson(needs.check_and_prepare.outputs.matrix_ssl) }}
+        os: ${{ fromJson(needs.check_and_prepare.outputs.matrix_os) }}
+        arch: ${{ fromJson(needs.check_and_prepare.outputs.matrix_combined) }}
+        runner_label: ['${{ needs.check_and_prepare.outputs.runner_label_mac_arm64 }}']
+        exclude:
+        # Mac self-hosted runner shouldn't run Linux or Windows tests.
+        - os: ubuntu-latest
+          runner_label: ${{ needs.check_and_prepare.outputs.runner_label_mac_arm64 }}
+        - os: windows-latest
+          runner_label: ${{ needs.check_and_prepare.outputs.runner_label_mac_arm64 }}
+        # For Mac, don't run x64 tests on arm64 runner.
+        - os: macos-12
+          arch: x64
+          runner_label: ${{ needs.check_and_prepare.outputs.runner_label_mac_arm64 }}
+        # Until we support building openssl from source, we can't link to system
+        # openssl when cross-compiling, so exclude openssl from mac arm64 testing.
+        - os: macos-12
+          ssl_variant: openssl
+          runner_label: ${{ needs.check_and_prepare.outputs.runner_label_mac_arm64 }}
+    steps:
+      - name: Clean up previous run
+        shell: bash
+        if: ${{ contains(needs.check_and_prepare.outputs.matrix_os, matrix.build_os) }}
+        run: |
+          echo "Cleaning up previous run"
+          rm -rf "${{ github.workspace }}"/*
+      - uses: actions/checkout@v2
+        with:
+          ref: ${{needs.check_and_prepare.outputs.github_ref}}
+      - name: Download Desktop integration tests artifact
+        if: ${{ contains(needs.check_and_prepare.outputs.matrix_os, matrix.build_os) }}
+        uses: actions/download-artifact@v2.0.8
+        with:
+          path: testapps
+          name: testapps-desktop-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.ssl_variant }}
+      # Omit all of the prerequisites steps; we ensure that our self-hosted runners
+      # are configured with all prereqs already installed.
+      - name: Create keychain (macOS)
+        if: ${{ runner.os == 'macOS' }}
+        shell: bash
+        run: |
+          echo "Creating temporary keychain"
+          # Create a local keychain on Mac:
+          # Clean up previous temp keychain, if any.
+          security delete-keychain tmp-keychain 2> /dev/null || true
+          # Create temp keychain file and unlock it.
+          # (Avoid passing in -p on command line by using interactive mode.)
+          # Also set it to default settings so there is no unlock timeout.
+          security -i <<EOF
+          create-keychain -p ${{ secrets.TEST_SECRET }} tmp-keychain
+          set-keychain-settings tmp-keychain
+          unlock-keychain -p ${{ secrets.TEST_SECRET }} tmp-keychain
+          EOF
+          # Change the keychain list and default keychain to the temp keychain.
+          security list-keychains -d user -s tmp-keychain
+          security default-keychain -s tmp-keychain
+      - name: Restore google-services files
+        shell: bash
+        run: |
+          python scripts/gha/restore_secrets.py --passphrase_file=- --artifact testapps <<EOF
+          ${{ secrets.TEST_SECRET }}
+          EOF
+      - name: Run Desktop integration tests
+        shell: bash
+        run: |
+          if [[ '${{ matrix.runner_label }}' == '${{ needs.check_and_prepare.outputs.runner_label_mac_arm64 }}' ]]; then
+            # Mac ARM64 only: Use arch -arm64 prefix to ensure that the app is running on arm64.
+            cmd_prefix='arch -arm64'
+            # ARM Mac requires a firestore.json to specify the host as 127.0.0.1 rather than localhost.
+            # Otherwise the Firestore emulator cannot connect, probably because localhost is ipv6.
+            echo '{"emulators":{"firestore":{"port":"8080","host":"127.0.0.1"}}}' > firebase.json
+          fi
+          set -x
+          ${cmd_prefix} firebase emulators:exec --only firestore --project demo-example 'python scripts/gha/desktop_tester.py --testapp_dir testapps --logfile_name "desktop-${{ matrix.os }}-${{ matrix.arch}}-${{ matrix.ssl_variant }}"'
+          set +x
+        env:
+          USE_FIRESTORE_EMULATOR: true
+      - name: Delete keychain (macOS)
+        if: ${{ always() && runner.os == 'macOS' }}
+        shell: bash
+        run: |
+          # Remove the local keychain on Mac:
+          # Set back to the default login keychain.
+          security list-keychains -d user -s login.keychain
+          # Delete the temp keychain, if it exists.
+          security delete-keychain tmp-keychain || true
+      - name: Prepare results summary artifact
+        if: ${{ !cancelled() }}
+        shell: bash
+        run: |
+          if [ ! -f testapps/test-results-desktop-${{ matrix.os }}-${{ matrix.arch}}-${{ matrix.ssl_variant }}.log.json ]; then
+            mkdir -p testapps && echo "__SUMMARY_MISSING__" > testapps/test-results-desktop-${{ matrix.os }}-${{ matrix.arch}}-${{ matrix.ssl_variant }}.log.json
+          fi
+      - name: Upload Desktop test results artifact
+        if: ${{ !cancelled() }}
+        uses: actions/upload-artifact@v2.2.2
+        with:
+          name: log-artifact
+          path: testapps/test-results-desktop-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.ssl_variant }}*
+          retention-days: ${{ env.artifactRetentionDays }}
+      - name: Download log artifacts
+        if: ${{ needs.check_and_prepare.outputs.pr_number && failure() && !cancelled() }}
+        uses: actions/download-artifact@v2.0.8
+        with:
+          path: test_results
+          name: log-artifact
+      - name: Update PR label and comment
+        if: ${{ needs.check_and_prepare.outputs.pr_number && failure() && !cancelled() }}
+        run: |
+          python scripts/gha/it_workflow.py --stage progress \
+            --token ${{github.token}} \
+            --issue_number ${{needs.check_and_prepare.outputs.pr_number}}\
+            --actor ${{github.actor}} \
+            --commit ${{needs.check_and_prepare.outputs.github_ref}} \
+            --run_id ${{github.run_id}}
+      - name: Summarize test results
+        if: ${{ !cancelled() }}
+        shell: bash
+        run: |
+          cat testapps/test-results-desktop-${{ matrix.runner_label }}-${{ matrix.ssl_variant }}.log
+          if [[ "${{ job.status }}" != "success" ]]; then
+            exit 1
+          fi
+      - name: Clean up after this run
+        shell: bash
+        if: ${{ always() }}
+        run: |
+          echo "Cleaning up after this run"
+          rm -rf "${{ github.workspace }}"/*
+      
   test_android:
     name: test-android-${{ matrix.build_os }}-${{ matrix.android_device }}
     needs: [check_and_prepare, build_android]
@@ -1154,7 +1331,7 @@ jobs:
 
   summarize_results:
     name: "summarize-results"
-    needs: [check_and_prepare, test_desktop, test_android, test_ios, test_tvos]
+    needs: [check_and_prepare, test_desktop, test_desktop_custom_runners, test_android, test_ios, test_tvos]
     runs-on: ubuntu-latest
     if: ${{ !cancelled() }}
     steps:
