If the zip file can't be downloaded, just skip that step.

diff --git a/.github/workflows/update-dependencies.yml b/.github/workflows/update-dependencies.yml
--- a/.github/workflows/update-dependencies.yml
+++ b/.github/workflows/update-dependencies.yml
@@ -134,25 +134,25 @@ jobs:
               curl -H 'Authorization: token ${{ github.token }}' -L -f "${try_url}" -o "${ziptmp}/Firebase.zip" 2> /dev/null && break
             done
             if [[ "${try_url}" == "error" ]]; then
-              echo "::error ::Could not download Firebase iOS prebuilt zip file."
+              echo "::error ::Could not download Firebase iOS prebuilt zip file, skipping Swift headers."
+            else
+              cd "${ziptmp}"
+              echo "Unzipping..."
+              unzip -q Firebase.zip '*-Swift.h'
+              cd -
+              # Copy all *-Swift.h header files into ios_pod/swift_headers/
+              echo "Copying headers..."
+              find "${ziptmp}" -name '*-Swift.h' -print0 | xargs -0 -n 1 -J REPLACETEXT cp -f REPLACETEXT ios_pod/swift_headers/
+              copyright_line="// Copyright $(date +%Y) Google LLC"
+              # Add a note to each file about its source.
+              for ios_header in ios_pod/swift_headers/*.h; do
+                if ! grep -q "^// Copied from Firebase iOS SDK" "${ios_header}"; then
+                  sed -i~ "s|^// Generated by Apple Swift|${copyright_line}\n// Copied from Firebase iOS SDK ${core_version}.\n\n// Generated by Apple Swift|" "${ios_header}"
+                fi
+                python3 scripts/format_code.py --f "${ios_header}"
+              done
             fi
-            cd "${ziptmp}"
-            echo "Unzipping..."
-            unzip -q Firebase.zip '*-Swift.h'
-            cd -
-            # Copy all *-Swift.h header files into ios_pod/swift_headers/
-            echo "Copying headers..."
-            find "${ziptmp}" -name '*-Swift.h' -print0 | xargs -0 -n 1 -J REPLACETEXT cp -f REPLACETEXT ios_pod/swift_headers/
-            copyright_line="// Copyright $(date +%Y) Google LLC"
-            # Add a note to each file about its source.
-            for ios_header in ios_pod/swift_headers/*.h; do
-              if ! grep -q "^// Copied from Firebase iOS SDK" "${ios_header}"; then
-                sed -i~ "s|^// Generated by Apple Swift|${copyright_line}\n// Copied from Firebase iOS SDK ${core_version}.\n\n// Generated by Apple Swift|" "${ios_header}"
-              fi
-              python3 scripts/format_code.py --f "${ios_header}"
-            done
             rm -rf ${ziptmp}
-
           elif [[ ${{ github.event.inputs.updateAndroid }} -eq 1 ]]; then
             # Update Android only
             echo "Updating Android dependencies only"
